import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    environment: 'node',
    include: [
      'src/lib/reportAdapters/reportRules.test.ts',
      'src/lib/reportAdapters/reportViewModel.test.ts',
      'src/lib/reportAdapters/usRent.test.ts',
      'src/lib/reportAdapters/validateAndRepair.test.ts',
      'src/lib/reportAdapters/detectPropertyCategory.test.ts',
      'src/lib/reportAdapters/effectiveReportMode.test.ts',
      'src/lib/reportAdapters/reportVariant.test.ts',
      'src/lib/reportAdapters/buildingDetails.test.ts',
      'src/lib/reportAdapters/buildingDetails.cross.test.ts',
      'src/lib/reportAdapters/buildingDetails.winbro.test.ts',
      'src/lib/reportAdapters/photoReviewAreas.test.ts',
      'src/lib/reportAdapters/Fallbacks.test.ts',
      'src/components/us/BuildingRentReport.guards.test.ts',
      'src/lib/reportAdapters/saleEvidenceOnly.test.ts',
      'src/lib/reportAdapters/zillowMonthlyPaymentGuards.test.ts',
      'src/lib/reportAdapters/zillowSaleDataIntegrity.test.ts',
      'src/lib/reportAdapters/zillowHoaKnown.test.ts',
      'src/content/extractors/contract.test.ts',
      'src/content/extractors/zillow.modeDetection.test.ts',
      'src/content/extractors/zillow.extraction.test.ts',
      'src/content/extractors/multiUnitGuard.test.ts',
      'src/content/extractors/studioSafety.test.ts',
      'src/content/extractors/galleryCounter.test.ts',
      'src/content/extractors/buildingPathC.test.ts',
      'src/content/extractors/roofFallback.test.ts',
      'src/content/extractors/listenerIntegrity.test.ts',
      'src/content/extractors/galleryOpenerDiagnostics.test.ts',
      'src/content/extractors/galleryIncidentReproduction.test.ts',
      'src/content/extractors/galleryCloseContract.test.ts',
      'src/content/extractors/galleryOpenFailDiagnostics.test.ts',
      'tests/extension.buildingFields.test.ts',
      'tests/extension.rentalCostCalculator.test.ts',
      'supabase/functions/analyze/minimalContradictionGuard.test.ts',
      'supabase/functions/analyze/rule6.test.ts',
      'supabase/functions/analyze/multiUnitBuildingDataFlow.test.ts',
      'supabase/functions/analyze/derivedTotalIncludesHoa.test.ts',
      'supabase/functions/analyze/mergeVisualAnalysis.test.ts',
      'supabase/functions/analyze/step2Retry.test.ts',
      'supabase/functions/analyze/creditsLifecycle.test.ts',
      'supabase/functions/analyze/step1BatchPartial.test.ts',
      'supabase/functions/analyze/analysisRecovery.test.ts',
      'src/lib/reportAdapters/photoFieldsCompatibility.test.ts',
      'src/lib/reportAdapters/saleScoreConsistency.test.ts',
      'src/lib/reportAdapters/imageDedup.test.ts',
      'supabase/functions/analyze/imageDedup.test.ts',
      'src/lib/reportAdapters/basicReport.test.ts',
      'src/components/report/NewReportUI.layout.test.ts',
    ],
  },
});